name: publish-nuget

on:
  push:
    tags:
    - v*
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/Rdz.Net.Library.sln'
      TEST_PROJECT: 'src/Rdz.Net.Library.Tests/Rdz.Net.Library.Tests.csproj'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Install xmldocmd documentation generator
      run: dotnet tool install xmldocmd -g

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    
    - name: Test
      run: dotnet test $TEST_PROJECT --configuration $BUILD_CONFIG --no-build --no-restore

    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/heads/master')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
